services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NITRO_HOST: 0.0.0.0
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped